### ISSUE TITLE
NPE when creating / using CloudStorage API

### ISSUE THREAD

**Issue by rmuller** [CloudRail/cloudrail-si-java-sdk#10]
I am using this simple code snippet (which works btw). Two NPE's are thrown (see below)

Using version 2.9.0 (Java 1.8.0_112).

```
CloudRail.setAppKey("***");
CloudStorage onedrive = new OneDrive(this::consoleOpenAndAwait, 
    "***", 
    "***", 
    "https://login.live.com/oauth20_desktop.srf", 
    "OneDrive");
List<CloudMetaData> files =  onedrive.getChildren("/");
files.forEach(f -> log.info(f));
```
Exceptions:

```
Exception in thread "Thread-2" java.lang.NullPointerException
	at com.cloudrail.si.statistics.Statistics.sendStatistics(Statistics.java:100)
	at com.cloudrail.si.statistics.Statistics.addCall(Statistics.java:74)
	at com.cloudrail.si.statistics.ReportCallTask.run(ReportCallTask.java:34)
... everything goes well, after a while:
Exception in thread "Timer-0" java.lang.NullPointerException
	at com.cloudrail.si.statistics.Statistics.sendStatistics(Statistics.java:100)
	at com.cloudrail.si.statistics.SendStatisticsTask.run(SendStatisticsTask.java:11)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by PatrickStoklasa** [comment]
Thank you for reporting the issue! We just pushed a new version (2.9.1) that should solve the problem. Let me know if it worked for you.

**Comment by rmuller** [comment]
That is fast! :)

Yes, exceptions are gone. First tests run successfully!

Thanks for the great and responsive service.
