### ISSUE TITLE
RuntimeException in Dropbox.login() after authentication

### ISSUE THREAD

**Issue by devfootageone** [CloudRail/cloudrail-si-java-sdk#13]
i try to integrate your sample with two step authorisation in my project.
-> https://www.youtube.com/watch?v=09McPM1NYv8&feature=youtu.be
first step works fine but after closing dropbox authentication in my browser a got following exception in "auth/complete" handler.
java.lang.RuntimeException: ServiceCode Error in function checkAuthentication at 3: awaitCodeRedirect $L1 $L0 ? $P0.redirectUri 
	at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:127)
	at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
	at com.cloudrail.si.services.Dropbox.login(Dropbox.java:1239)
	at ........api.controllers.CloudRailController.handleAuthRequest(CloudRailController.java:77)

**Comment by devfootageone** [comment]
the problem is in RedirectReceiver

with request.getRequestURI() you get URI without parameters but parameters is the important part in return string!
i changed my code of my RedirectReceiver:
return "http://not.important.host/?" + request.getQueryString();

it works!
thx support for help understanding how RedirectReceiver works!

**Comment by PatrickStoklasa** [comment]
Glad to hear that it is working!

**Comment by Wajeehkhan123** [comment]
i try to integrate using your sample at 
https://github.com/CloudRail/cloudrail-si-dotnet-sdk/blob/master/Examples/UnifiedCloudStorage/UnifiedCloudStorage/Program.cs

 but getting error 
Uri  ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Com.CloudRail.SI.ServiceCode.Commands.AwaitCodeRedirect.Execute(Sandbox environment, Object[] parameters)
   at Com.CloudRail.SI.ServiceCode.Interpreter.Run()
   --- End of inner exception stack trace ---
   at Com.CloudRail.SI.ServiceCode.Interpreter.Run()
   at Com.CloudRail.SI.ServiceCode.Interpreter.CallFunction(String functionName, Object[] parameters)
   at Com.CloudRail.SI.Services.Dropbox.Login()
